# Stage 1
FROM maven:3.9.9-eclipse-temurin-11-alpine AS builder

# Add labels to the image to filter out if we have multiple application running
LABEL app=bankapp

WORKDIR /src

COPY . .
# Build application and skip test cases

RUN mvn clean install -DskipTests=true

# Stage 2
FROM alpine/java:22-jdk AS deploy

# Copy build from stage 1 (builder)
COPY --from=builder /src/target/*.jar /src/target/bankapp.jar

# Expose application port 
EXPOSE 8080

# Start the application
ENTRYPOINT ["java", "-jar", "/mavensrc/target/bankapp.jar"]
